[Autologin]
Relogin=false
Session=xfce

[General]
HaltCommand=/usr/bin/systemctl poweroff
RebootCommand=/usr/bin/systemctl reboot

[Theme]
Current=Sugar-Candy

[User]
MaximumUid=60000
MinimumUid=1000
