#!/bin/bash

RED="\e[1;91m"
GREEN="\e[1;92m"
RESET="\e[0m"

clear 

echo -e "${RED} O "

sleep 2

clear

echo -e "${RED} O O "

sleep 2

clear 

echo -e "${RED} O O O "

sleep 2

clear 

echo -e "${RED} O O O O "

sleep 2

clear

echo -e "${RED} O O O O O "

sleep 8 

clear

echo -e "${GREEN} IT'S LIGHTS OUT AND AWAY WE GO !!!"

echo -e "${RESET}  "
